### PR TITLE
Fix typo and bugs, also update tensorflow API to v2.13.0

### PR DESCRIPTION
**Pull request by heng-yuwen**
Done correcting and updating the code from 1-Computer-Vision/Exercises/1-1-1-Choosing-Metrics/2022-07-25-Choosing-Metrics-IoU.ipynb to 1-Computer-Vision/Exercises/1-3-1-Logistic-Regression/2022-08-27-Logistic-Regression.ipynb

### CODE REVIEW

**Comment by heng-yuwen** [comment]
Hi @jonathanloganmoran , maybe I changed too much now, and it should not merge to your repo directly. I have gone to 1.3.1 while reviewing your code and fixing the issues in your notebook. If possible, maybe you can view my updates and merge the desired changes you like?

**Comment by jonathanloganmoran** [comment]
> Hi @jonathanloganmoran , maybe I changed too much now, and it should not merge to your repo directly. I have gone to 1.3.1 while reviewing your code and fixing the issues in your notebook. If possible, maybe you can view my updates and merge the desired changes you like?

Hello @heng-yuwen. Firstly, thank you very, very much for your contributions. It is wonderful to have your work here. 

I have reviewed your changes up until commit #7f43edd and wanted to add additional commits into this PR #49 before merging. To do so, I created branch [`pr49-course-1-revision-1-heng-yuwen`](https://github.com/jonathanloganmoran/ND0013-Self-Driving-Car-Engineer/tree/pr49-course-1-revision-1-heng-yuwen) and have finished making the appropriate changes (for now). Can you possibly instruct me on how we may continue with the work on this new branch as the progress point for PR #49?

**Comment by heng-yuwen** [comment]
Hi @jonathanloganmoran, thanks for adding the comments. I think we'd better merge this pull request first, and then you can add the comments to the master branch, so that we can create another pull request and continue our contribution. 

In fact, this is the first time I work with notebook format on github. Next time I will follow your PR template and create pull request once per tutorial file.

**Comment by jonathanloganmoran** [comment]
@heng-yuwen: Happy to hear that you are able to successfully work with the `.ipynb` files — I found [ReviewNB](https://app.reviewnb.com/jonathanloganmoran/ND0013-Self-Driving-Car-Engineer/pull/49) an extremely useful resource for diff'ing your changes here.

I think we should continue with your latter suggestion, i.e., open a new PR from the branch I have created ([`pr49-course-1-revision-1-heng-yuwen`](https://github.com/jonathanloganmoran/ND0013-Self-Driving-Car-Engineer/tree/pr49-course-1-revision-1-heng-yuwen). This allows us to include all of your changes and mine, aside from your most recent commit [7f43edd](https://github.com/jonathanloganmoran/ND0013-Self-Driving-Car-Engineer/pull/49/commits/7f43eddd212c931ed95aabc287bb6cc034a86017) which contains the TensorFlow API changes I am unable to review at this moment.

If you think this is appropriate, I will close this PR and open a new PR from my working branch with you as the Reviewer.

**Comment by heng-yuwen** [comment]
Hi @jonathanloganmoran, Please do so, and I am happy to continue my review once it is done.

**Comment by jonathanloganmoran** [comment]
> Hi @jonathanloganmoran, Please do so, and I am happy to continue my review once it is done.

Wonderful, I'll go ahead and do that now.

**Pull request closed without merging**
